## Uses Markov Chain. Very cool. Converted from GDScript (Godot Game Engine) to Python.

import random

CONTINUE_TOKEN : str = "Y"
BREAK_TOKEN : str = "N"

START_TOKEN : str = "^"
NULL_TOKEN : str = "$"

WEIGHT_INCREMENT : int = 1

order : int = -1

min_char_length : int = -1
max_char_length : int = -1


# Names generated by ChatGPT
# and also pulled from 1000randomnames.com
names : list[str] = [
    "Aaliyah", "Aaron", "Abby", "Abel", "Abigail", "Adalay", "Adele", "Adonis", "Adrian", "Ahmad",
    "Aiden", "Aitana", "Alani", "Alanna", "Alena", "Alexander", "Alondra", "Alvaro", "Amani", "Amara",
    "Amari", "Ameer", "Amelia", "Amilia", "Amir", "Amora", "Andrew", "Angel", "Aniya", "Anna",
    "Ansley", "Aria", "Ariadne", "Ariella", "Aries", "Arthur", "Asher", "Athena", "Audrey", "August",
    "Aurelia", "Autumn", "Ava", "Avery", "Avianna", "Axel", "Axton", "Ayden", "Ayla", "Barrett",
    "Beau", "Beckett", "Bella", "Benjamin", "Bennett", "Benson", "Bodie", "Bowen", "Brandon", "Brantley",
    "Briana", "Brody", "Brooks", "Brynlee", "Bryson", "Caleb", "Cameron", "Camila", "Camilo", "Carla",
    "Carlos", "Caroline", "Carter", "Celine", "Chance", "Charles", "Charlie", "Charlotte", "Chaya", "Chloe",
    "Christian", "Christopher", "Clarissa", "Cody", "Colton", "Cooper", "Corey", "Cruz", "Cullen", "Daleyza",
    "Dallas", "Daniel", "Dante", "David", "Dax", "Deacon", "Declan", "Delilah", "Desmond", "Devin",
    "Dominic", "Dominick", "Dream", "Dylan", "Easton", "Edgar", "Edwin", "Elena", "Eli", "Eliana",
    "Elias", "Elijah", "Elizabeth", "Ella", "Ellie", "Elliott", "Elora", "Ember", "Emelia", "Emerson",
    "Emery", "Emily", "Emma", "Emmett", "Emmitt", "Enzo", "Estella", "Estelle", "Esther", "Ethan",
    "Eva", "Evangeline", "Evelyn", "Everett", "Ezekiel", "Ezequiel", "Ezra", "Finley", "Finn", "Finnegan",
    "Gabriel", "Gael", "Gage", "Gavin", "Gemma", "Genesis", "Giana", "Gianna", "Gideon", "Grace",
    "Gracelyn", "Graham", "Greyson", "Gunner", "Hale", "Halia", "Harper", "Hazel", "Henry", "Hezekiah",
    "Holden", "Hudson", "Hunter", "Ian", "Isaac", "Isabella", "Isaiah", "Isaias", "Isla", "Ismael",
    "Ivory", "Ivy", "Jack", "Jackson", "Jacob", "Jacoby", "Jaden", "Jaiden", "James", "Jameson",
    "Janiyah", "Jason", "Jax", "Jaxon", "Jaxson", "Jay", "Jayden", "Jayla", "Joelle", "John",
    "Jolie", "Jonah", "Jonathan", "Jordan", "Jordyn", "Jose", "Joseph", "Joshua", "Josiah", "Journee",
    "Journi", "Joy", "Juan", "Judah", "Jude", "Julian", "Kaiden", "Kailani", "Kailyn", "Kaine",
    "Kaison", "Kaleb", "Kali", "Kaliyah", "Kallie", "Kallum", "Kameron", "Kamila", "Kannon", "Kari",
    "Karson", "Karsyn", "Karter", "Kasen", "Kash", "Kashton", "Katalina", "Katelyn", "Kato", "Kayson",
    "Keeva", "Kehlani", "Kenia", "Kenneth", "Kensley", "Kenzie", "Khadija", "Khloe", "Kian", "Kiana",
    "Kiara", "Kimber", "Kimora", "King", "Kingston", "Kinsley", "Kiyomi", "Klay", "Knox", "Koa",
    "Koda", "Kora", "Kourtney", "Kye", "Kylian", "Kylie", "Kyrie", "Kyson", "Lacy", "Lana",
    "Landon", "Lane", "Laney", "Lara", "Layla", "Leah", "Ledger", "Legacy", "Legend", "Leilani",
    "Lenia", "Lennox", "Leo", "Leon", "Leona", "Levi", "Lia", "Liam", "Liana", "Lila",
    "Lilah", "Lilia", "Lilly", "Lily", "Lincoln", "Livia", "Logan", "Lorelai", "Louis", "Luca",
    "Lucas", "Lucy", "Luke", "Luna", "Macie", "Madelyn", "Madison", "Maeve", "Major", "Malachi",
    "Malakai", "Malcolm", "Malia", "Malik", "Maren", "Maria", "Mariam", "Marlee", "Mason", "Mateo",
    "Mathew", "Matthew", "Maverick", "Mavis", "Maxwell", "Maya", "Mckenzie", "Melany", "Mercy", "Messiah",
    "Mia", "Micah", "Michael", "Mila", "Milani", "Milano", "Milena", "Miles", "Milo", "Mina",
    "Mohammad", "Monica", "Mya", "Nadia", "Naomi", "Nasir", "Natalia", "Nathan", "Nehemiah", "Neriah",
    "Nicholas", "Nico", "Nikolai", "Noah", "Noemi", "Nola", "Nolan", "Nora", "Nour", "Nova",
    "Nylah", "Oakley", "Oaklynn", "Oliver", "Olivia", "Ollie", "Owen", "Paloma", "Paris", "Paul",
    "Paula", "Paulina", "Penelope", "Pierce", "Pinky", "Pranav", "Preston", "Princess", "Quinn", "Rafael",
    "Raina", "Rayan", "Rayna", "Rayne", "Reece", "Regina", "Reid", "Remi", "Rhys", "River",
    "Robert", "Rocco", "Roman", "Rory", "Rosalie", "Rowan", "Ruby", "Ryan", "Ryder", "Rylie",
    "Sadie", "Samantha", "Samara", "Samuel", "Sania", "Santiago", "Sariyah", "Sasha", "Savannah", "Sawyer",
    "Saylor", "Scarlett", "Sean", "Sebastian", "Serenity", "Sienna", "Silas", "Skyler", "Sloane", "Sofia",
    "Sophia", "Soren", "Stella", "Sylvia", "Talia", "Taliyah", "Tatum", "Teresa", "Theodore", "Thomas",
    "Tristan", "Tucker", "Vada", "Valerie", "Veda", "Victoria", "Walker", "Walter", "Warren", "Waylon",
    "Wesley", "Willa", "William", "Willow", "Wyatt", "Xavier", "Yara", "Yaretzi", "Yelena", "Zackary",
    "Zadie", "Zadok", "Zahra", "Zid", "Zainab", "Zamir", "Zander", "Zane", "Zaniah", "Zaniyah",
    "Zara", "Zari", "Zaria", "Zariah", "Zariyah", "Zavier", "Zayd", "Zayda", "Zaylee", "Zelda",
    "Zen", "Zendaya", "Zev", "Zion", "Zita", "Zola", "Zora", "Zoya", "Zula", "Zunairah",
    "Zuri", "Zyaire", "Bianca", "Alora", "Raelyn", "Mauricio", "Hendrix", "Josephine", "Manuel", "Nalani",
    "Axl", "Harris", "Donovan", "Crystal", "Brianna", "Kai", "Kenna", "Kristian",
    "Saul", "Violette", "Boston", "Jayce", "Adriana", "Nia", "Ocean", "Arya",
    "Russell", "Mae", "Stephanie", "Santos", "Freyja", "Dangelo", "Tessa", "Jasiah",
    "Damien", "Madilyn", "Wilder", "Andres", "Calliope", "Cecilia", "Jasper", "Amira",
    "Adler", "Maximilian", "Henley", "Remington", "Davis", "Heaven", "Dorian", "Demi",
    "Mallory", "Matteo", "Fiona", "Roy", "Morgan", "Allan", "Marcos", "Leia", "Magnus",
    "Ibrahim", "Allie", "Treasure", "Watson", "Noor", "Braylon", "Kenna", "Irene",
    "Hayley", "Cade", "Brinley", "Amina", "Samson", "Parker", "Benicio", "Iliana",
    "Eileen", "Connor", "Cheyenne", "Maximo", "Roselyn", "Frederick", "Sergio", "Conor",
    "Jaxton", "Layne", "Jillian", "Eugene", "Madilyn", "Harmoni", "Cory", "Alma",
    "Allyson", "Izaiah", "Melina", "Abram", "Jaime", "Aarya", "Giovanni", "Kathryn",
    "Kylan", "Fatima", "Lylah", "Phillip", "Harlow", "Tru", "Michaela", "Maxton",
    "Alessandra", "Kelvin", "Itzel", "Alonso", "Avayah", "Brian", "Jamie", "Eliza",
    "Max", "Kori", "Cora", "Dario", "Beatrice", "Khalil", "Whitney", "Lian",
    "Paisley", "Peyton", "Alec", "Emilia", "Bridger", "Charli", "Ophelia", "Emanuel",
    "Macy", "Marceline", "Flynn", "Tyson", "Nicole", "Mckinley", "Raven", "Valentin",
    "Bryan", "Lyla", "Veronica", "Marcellus", "Saoirse", "Joey", "Brittany", "Aliyah",
    "Duke", "Dulce", "Atreus", "Jaelynn", "Elisha", "Brielle", "Yahir", "Haisley",
    "Kyla", "Colby", "Gordon", "Jazlyn", "Bobby", "Justice", "Ace", "Kailey",
    "Jaylen", "Kataleya", "Eliezer", "Ariana", "Rodney", "Analia", "Phoenix", "Royalty",
    "Cyrus", "Saige", "Tanner", "Celeste", "Nathanael", "Novah", "Brylee", "Brayden",
    "Kamiyah", "Adler", "Jill", "Leighton", "Kendrick", "Genevieve", "Romina", "Theodora",
    "Augustine", "Marina", "Piper", "Omar", "Adalee", "Jaxxon", "Camryn", "Apollo",
    "Rosalyn", "Ariya", "Adaline", "Salvatore", "Ensley", "Carson", "Natalie", "Quentin",
    "Remy", "Aspen", "Cohen", "Norah", "Amaia", "Seth", "Lilith", "Dahlia",
    "Grady", "Julieta", "Kamden", "Rose", "Jair", "Hattie", "Reginald", "Isabel",
    "Bellamy", "Luella", "Emely", "Kabir", "Addilyn", "Winston", "Coraline", "Jeremias",
    "Annie", "Wynter", "Bryant", "Hadlee", "Araceli", "Krew", "Maliyah", "Jayceon",
    "Jocelyn", "Wallace", "Sylvie", "Franklin", "Florence", "Kole", "Shay", "Alivia",
    "Aislinn", "Kolton", "Rhea", "Calvin", "Dustin", "Marilyn", "Amelie", "Ari",
    "Jianna", "Lucca", "Liliana", "Gustavo", "Elaine", "Augustus", "Ellis", "Langston",
    "Marisol", "Bristol", "London", "Amaya", "Braden", "Eliseo", "Julio", "Laylani",
    "Mark", "Fernanda", "Turner", "Lyric", "Emilio", "Leandro", "Waverly", "Dane",
    "Lacey", "Kellen", "Brooklynn", "Ronin", "Oakleigh", "Thaddeus", "Ahmir", "Catalina",
    "Nelson", "Edward", "Aleah", "Alexis", "Roland", "Penny", "Mariana", "Oscar",
    "Ivan", "Madeline", "Riggs", "Elsa", "Kayleigh", "Alaric", "Maggie", "Bentley",
    "Cassidy", "Ada", "Odin", "Gracelynn", "Tony", "Atlas", "Melody", "Fisher",
    "Rebecca", "Alaia", "Wells", "Mira", "Jaxen", "Joziah", "Ellison", "Hayden",
    "Danielle", "Judson", "Matilda", "Journey", "Paityn", "Zeus", "Arabella", "Valentino",
    "Abdullah", "Amber", "Cash", "Kaylie", "Kyler", "Banks", "Kaisley", "Aydin",
    "Elena", "Saint", "Aliza", "Dalton", "Pearl", "Angelo", "Colson", "Hugh",
    "Xzavier", "Laura", "Adalyn", "Lee", "Aviana", "Garrett", "Carl", "Amanda",
    "Azalea", "Heath", "Erik", "Zoie", "Kyree", "Valeria", "Myles", "Jada",
    "Dior", "Chandler", "Jabari", "Matias", "Paola", "Branson", "Casen", "Selena",
    "Alexandra", "Arlo", "Leilany", "Zain", "Baylee", "Rome", "Kendall", "Clay",
    "Catherine", "Everest", "Vera", "Kane", "Anaya", "Paxton", "Layton", "Jimena",
    "Imani", "Helena", "Jerry", "Darius", "Travis", "Neil", "Octavia", "Justin",
    "Etta", "Caiden", "Kairo", "Amoura", "Daxton", "Astrid", "Miley", "Omari",
    "Ryker", "Juelz", "Brecken", "Luciana", "Otto", "Holly", "Sophie", "Amos",
    "Palmer", "Wesson", "Hakeem", "Berkley", "Jared", "Julia", "Abraham", "Alberto",
    "Jalen", "Nyla", "Bryce", "Denver", "Elian", "Cara", "Poppy", "Baylor",
    "Averie", "Dilan", "Andrea", "Briggs", "Raegan", "Gwendolyn", "Noe", "Alexandria",
    "Kamari", "Steven", "Viviana", "Uriah", "Miranda", "Enoch", "Ty", "Stephen",
    "Jeffrey", "Alfred", "Alayna", "Kyng", "Megan", "Kenzo", "Bailee", "Carmelo",
    "Coen", "Isabela", "Rocky", "Keegan", "Moses", "Dash", "Bo", "Brooklyn",
    "Lennon", "Lyanna", "Anakin", "Mabel", "Donald", "Jazmine", "Harley", "Niklaus",
    "Yasmin", "Sylas", "Mario", "Fernando", "Frida", "Victor", "Trent", "Faye",
    "Dean", "Cain", "Cannon", "Trinity", "Guillermo", "Leonel", "Eloise", "Armani",
    "Jase", "Talon", "Ayleen", "Alexa", "Onyx", "Della", "Novalee", "Emmanuel",
    "Skye", "Sarai", "Abner", "Evie", "Landyn", "Everly", "Issac", "Tiana",
    "Ares", "Sabrina", "Maci", "Kairi", "Theo", "Trenton", "Kayden", "Lyra",
    "Elodie", "Emmie", "Nataly", "Sage", "Callahan", "Harleigh", "Davian", "Gabrielle",
    "Spencer", "Malayah", "Cadence", "Bethany", "Azariah",
    "Fritz",
]


chain : dict[str, dict] = {}


def _build_chain() -> None:
    for name in names:
        current_name : str = ""

        for i in range(order):
            current_name += START_TOKEN
        current_name += name.lower()

        for i in range(len(current_name) - order):
            key : str = ""

            for j in range(order):
                key += current_name[i + j]

            next_letter : str = current_name[i + order]

            if key not in chain:
                chain[key] = {}
                chain[key][next_letter] = WEIGHT_INCREMENT
            else:
                if next_letter not in chain[key]:
                    chain[key][next_letter] = WEIGHT_INCREMENT
                else:
                    chain[key][next_letter] = chain[key][next_letter] + WEIGHT_INCREMENT


def _generate_name() -> str:
    character_count : int = 0
    generated_name : str = ""

    key : str = ""
    for _i in range(order):
        key += START_TOKEN

    while character_count < max_char_length:
    
        if key not in chain:
            break

        next_letter : str = _get_next_letter(key)

        if next_letter == NULL_TOKEN:
            if character_count > min_char_length:
                break
            else:
                while next_letter == NULL_TOKEN:
                    next_letter = _get_next_letter(key)

        generated_name += next_letter
        key = key[1:] + next_letter
        character_count += 1

    return generated_name.capitalize()


def _get_next_letter(key : str) -> str:
    possible_next_letters : dict[str, int] = chain[key]

    letters : list[str] = list(possible_next_letters.keys())
    weights : list[int] = list(possible_next_letters.values())

    next_letter = random.choices(letters, weights)

    return next_letter[0]




print("(Higher = more realistic name, but recommended is 3, because training data isn't enough.)")
order = int(input("Enter level of Order: "))
min_char_length = int(input("Enter minimum name length: "))
max_char_length = int(input("Enter maximum name length: "))

for num in [order, min_char_length, max_char_length]:
    if num <= 0:
        print("An entered value is smaller than or equal to 0. Don't do that.")
        print("Chain is now empty, and you can't generate a name.")
        break

_build_chain()


while 1:
    print("Generated name: %s" % _generate_name())
    sentinel = input("Continue? %s/%s: " % (CONTINUE_TOKEN, BREAK_TOKEN))
    
    if sentinel.upper() == CONTINUE_TOKEN:
        continue
    elif sentinel.upper() == BREAK_TOKEN:
        break
    
    break

